### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by TheMapSmith** [TheMapSmith/mastermind#1]
- [x] Add some language that the mastermind is for all skill levels
- [x] Add details about how the group will meet and how often
- [x] Add license
- [x] Add contributing

**Comment by TheMapSmith** [comment]
- [x] Hero image
- [x] Code of conduct
